Traceback (most recent call last):
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\skorczewskit\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ts = np.array([0.1,0.42, 0.75, 1.1, 1.4, 1.7, 2.0, 2.35, 2.67, 3.])
fs = np.array([1.75e-05, 1.6e-01, 5.9e-01, 7.0e-01, 5.7e-01, 3.95e-01, 2.6e-01, 1.6e-01, 1.0e-01, 6.3e-02])
plt.plot(ts,fs,'kd');

### delete below for exam

from scipy.optimize import curve_fit

def func(t,m,s):
    output=(1./(t*s*np.sqrt(2.*np.pi)))*np.exp(-(np.log(t)-m)**2/(2.*s**2))
    return(output)

popt, pcov = curve_fit(func,ts,fs,(0.1,0.1))
print(popt)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m ts [38;5;241m=[39m [43mnp[49m[38;5;241m.[39marray([[38;5;241m0.1[39m,[38;5;241m0.42[39m, [38;5;241m0.75[39m, [38;5;241m1.1[39m, [38;5;241m1.4[39m, [38;5;241m1.7[39m, [38;5;241m2.0[39m, [38;5;241m2.35[39m, [38;5;241m2.67[39m, [38;5;241m3.[39m])
[0;32m      2[0m fs [38;5;241m=[39m np[38;5;241m.[39marray([[38;5;241m1.75e-05[39m, [38;5;241m1.6e-01[39m, [38;5;241m5.9e-01[39m, [38;5;241m7.0e-01[39m, [38;5;241m5.7e-01[39m, [38;5;241m3.95e-01[39m, [38;5;241m2.6e-01[39m, [38;5;241m1.6e-01[39m, [38;5;241m1.0e-01[39m, [38;5;241m6.3e-02[39m])
[0;32m      3[0m plt[38;5;241m.[39mplot(ts,fs,[38;5;124m'[39m[38;5;124mkd[39m[38;5;124m'[39m);

[1;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

